swagger: "2.0"
info:
    title: PubSubServer REST API
    description: REST API for PubSubServer
    version: ""
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /publish:
        get:
            tags:
                - PubSubServer
            summary: publish PubSubServer
            operationId: PubSubServer#publish
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: integer
                        format: int64
            schemes:
                - http
