openapi: 3.0.3
info:
    title: PubSubServer REST API
    description: REST API for PubSubServer
    version: "1.0"
servers:
    - url: http://localhost:8080
paths:
    /publish:
        get:
            tags:
                - PubSubServer
            summary: publish PubSubServer
            operationId: PubSubServer#publish
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: integer
                                example: 7309079112215645287
                                format: int64
                            example: 1038579224786901761
components: {}
tags:
    - name: PubSubServer
      description: The PubSubServer service performs operations on messages.
