swagger: "2.0"
info:
    title: PubSubServer REST API
    description: REST API for PubSubServer
    version: ""
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /publish:
        post:
            tags:
                - PubSubServer
            summary: publish PubSubServer
            operationId: PubSubServer#publish
            parameters:
                - name: PublishRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/PubSubServerPublishRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: integer
                        format: int64
            schemes:
                - http
definitions:
    PubSubServerPublishRequestBody:
        title: PubSubServerPublishRequestBody
        type: object
        properties:
            roomID:
                type: string
                description: aaa
                example: Qui voluptate quaerat repellendus aliquid non.
        example:
            roomID: Atque a.
