// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package usecase

import (
	"database/sql"
	"github.com/wadda0714/Golang_PubSubServer/server/infra/query"
	"github.com/wadda0714/Golang_PubSubServer/server/infra/repository"
)

// Injectors from wire.go:

func GeneratedNewUserDI(db *sql.DB) User {
	userQuery := query.NewUser(db)
	userRepository := repository.NewUser(db)
	user := NewUser(userQuery, userRepository)
	return user
}
